//! PanYa - Leptos CSR frontend.
//!
//! A `cdylib` compiled to `wasm32-unknown-unknown` and bundled by Trunk; the
//! Tauri shell injects `window.__TAURI__` (services/tauri.rs is the only
//! module that touches it). Module layout: [`models`] mirrors the backend
//! wire types, [`contexts`] owns shared state, [`components`] renders, and
//! [`pages`] composes the root view.

mod components;
mod contexts;
mod models;
mod pages;
mod services;

use leptos::mount::mount_to_body;
use leptos::prelude::*;
use wasm_bindgen::prelude::wasm_bindgen;

/// WASM entry point invoked by the page generated by Trunk.
#[wasm_bindgen(start)]
pub fn start() {
    console_error_panic_hook::set_once();
    mount_to_body(|| view! { <pages::app::App /> });
}
